version: '3.3'

services:
  redis:
    image: redis:6.0
    restart: always
    ports:
      - "6379:6379"
    volumes: 
      - cache:/data
    environment:
      - REDIS_PASSWORD=senha-segura
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  cache:
