version: '3.1'
services:
  mongodb:
    container_name: poc-tabd
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: animal
    volumes:
      - "${HOME}/mongo_data:/data/db"
    ports:
      - "27017:27017"