spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: admin
      password: admin
      database: animal

##spring:
  ##data:
    ##mongodb:
      ##uri: mongodb+srv://daniel:1702051@cluster0.y89vhxb.mongodb.net/?retryWrites=true&w=majority
      ##database: fundatec
